### PR TITLE
Update and rename readme.md to README.md

### PR DESCRIPTION
**Pull request by imranaai**
What I changed:
```diff
+ Renamed the readme.md file to `README.md` for better visibility. 
+ Improvement in the License Section of the `README.md` file. 
+ Added `©` for better visibility of copyright.

### CODE REVIEW

**Comment by saket** [comment]
Is this a duplicate of https://github.com/saket/telephoto/pull/23?

**Comment by imranaai** [comment]
> Is this a duplicate of https://github.com/saket/telephoto/pull/23?

Yes, 
First by convention it is always in all caps,
Due to the human behaviour by which we always look for familiar objects,
And since most of the repositories have the README file all caps, thus it will be more easier to find this file.

**Comment by imranaai** [comment]
Yes it could be a duplicate, since I am new to open-source and GitHub please let me know if I have done something wrong. I am here to learn and improve.

**Comment by saket** [comment]
No worries and welcome!

You're right that most projects name their readme file in full caps, but AFAIK that's a holdover from the unix world where uppercase file names are listed above lowercase names by the `ls` command. I don't think this is needed anymore. I personally find `readme.md` more pleasing to my eyes. 🙂

**Comment by imranaai** [comment]
> No worries and welcome!
> 
> You're right that most projects name their readme file in full caps, but AFAIK that's a holdover from the unix world where uppercase file names are listed above lowercase names by the `ls` command. I don't think this is needed anymore. I personally find `readme.md` more pleasing to my eyes. 🙂

Yes thanks! that's something I learned today about unix. Otherwise you could have merged the part where I changed the License section to make it look better according to me.
Well you can let me know about your thoughts on the change in License section.

**Pull request closed without merging**
